#!/usr/bin/env python3
"""Generate metamcp/.env from example.env plus a bootstrap configuration.

Secrets are generated here and never printed: the point of a local instance is
that nothing sensitive ends up in a transcript. The generated values land in
metamcp/.env, which is gitignored.
"""
from __future__ import annotations

import base64
import os
import re
import secrets
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WORKSPACE_ROOT = Path(os.environ.get("WORKSPACE_ROOT", Path.home() / "Sviluppo"))
METAMCP = Path(os.environ.get("METAMCP_DIR", WORKSPACE_ROOT / "metamcp"))
ENV = METAMCP / ".env"
SECRETS_DIR = Path(os.environ.get("SECRETS_DIR", REPO / ".secrets"))

ADMIN_EMAIL = "admin@firecrest.local"

# Reuse the existing secrets if .env is already there, so re-running is safe and
# does not orphan the Postgres volume's user or existing API keys.
existing: dict[str, str] = {}
if ENV.exists():
    for line in ENV.read_text().splitlines():
        if "=" in line and not line.strip().startswith("#"):
            k, _, v = line.partition("=")
            existing[k.strip()] = v.strip()


def secret(name: str, length: int = 32, urlsafe: bool = True) -> str:
    if name in existing and existing[name]:
        return existing[name]
    raw = secrets.token_bytes(length)
    return base64.urlsafe_b64encode(raw).decode().rstrip("=") if urlsafe else raw.hex()


auth_secret = secret("BETTER_AUTH_SECRET", 48)
admin_password = existing.get("BOOTSTRAP_ADMIN_PASSWORD") or (
    base64.urlsafe_b64encode(secrets.token_bytes(18)).decode().rstrip("=")
)
pg_password = secret("POSTGRES_PASSWORD", 18)

template = (METAMCP / "example.env").read_text()

# Replace the placeholder secrets the example ships with.
template = template.replace(
    "BETTER_AUTH_SECRET=your-super-secret-key-change-this-in-production",
    f"BETTER_AUTH_SECRET={auth_secret}",
)
template = re.sub(r"^POSTGRES_PASSWORD=.*$", f"POSTGRES_PASSWORD={pg_password}",
                  template, flags=re.M)

# Override everything from the "USER CONFIGURATION" block to the end with our
# bootstrap configuration.
head, _, _ = template.partition("# USER CONFIGURATION")

bootstrap = f"""# USER CONFIGURATION
BOOTSTRAP_USER_EMAIL={ADMIN_EMAIL}
BOOTSTRAP_USER_NAME=Gabriele Vadala
BOOTSTRAP_USER_PASSWORD={admin_password}
BOOTSTRAP_RECREATE_USER=false
BOOTSTRAP_WARN_PASSWORD_CHANGE=false
# Registration must stay OPEN during the first boot. MetaMCP's bootstrap applies
# these controls *before* creating the bootstrap user, and it creates that user by
# calling its own sign-up endpoint — so setting either to true makes user creation
# fail with 422 FAILED_TO_CREATE_USER, which in turn makes the API key be skipped
# ("user not found") and leaves the instance unusable. Registration is disabled
# afterwards via the admin tool metamcp_set_signup_disabled; see docs/METAMCP.md.
BOOTSTRAP_DISABLE_REGISTRATION_UI=false
BOOTSTRAP_DISABLE_REGISTRATION_SSO=true

# One API key, owned by the admin. Its value is generated by MetaMCP at
# bootstrap and stored in the api_keys table; read it with
# scripts/read_metamcp_api_key.sh rather than regenerating it.
BOOTSTRAP_API_KEYS=[{{"name":"firecrest-workbench","is_public":false,"user_email":"{ADMIN_EMAIL}"}}]

# The namespace prompt 03 asks for. It starts empty and the FirecREST MCP
# server is attached to it through the MetaMCP admin MCP tools.
BOOTSTRAP_NAMESPACES=[{{"name":"firecrest-workbench","description":"FirecREST tools for the agentic workbench demo","is_public":false,"user_email":"{ADMIN_EMAIL}","update":true}}]

# The public endpoint, protected with the API key above.
BOOTSTRAP_ENDPOINTS=[{{"name":"firecrest-workbench","description":"Aggregated FirecREST endpoint","namespace":"firecrest-workbench","enable_auth":true,"enable_auth_query":false,"enable_auth_oauth":false,"is_public":false,"user_email":"{ADMIN_EMAIL}","update":true}}]
"""

ENV.write_text(head + bootstrap)
ENV.chmod(0o600)

SECRETS_DIR.mkdir(parents=True, exist_ok=True)
(SECRETS_DIR / "README.md").write_text(
    "# Local secrets\n\n"
    "Not committed — `.secrets/` is gitignored.\n\n"
    f"- `metamcp-admin-password.txt` — web UI login for {ADMIN_EMAIL}\n"
    "- `metamcp-api-key.txt` — API key for the MetaMCP endpoint\n"
)
(SECRETS_DIR / "metamcp-admin-password.txt").write_text(admin_password + "\n")
(SECRETS_DIR / "metamcp-admin-password.txt").chmod(0o600)

print(f"wrote {ENV} (mode 600)")
print(f"wrote {SECRETS_DIR / 'metamcp-admin-password.txt'} (mode 600)")
print(f"admin email: {ADMIN_EMAIL}")
print("no secret values printed; read them from the files above")
